//! Obfuscated cryptographic core for Liner HMAC signing.
//!
//! Provides HMAC-SHA256 computation over distinct obfuscated keys for
//! Cover URL signing, API request signing, and Monitor telemetry signing.
//! Keys are derived in memory per-call and zeroized immediately on drop.

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use zeroize::Zeroizing;

type HmacSha256 = Hmac<Sha256>;

// ==== BEGIN generated by scripts/gen-obfuscated-key.mjs — DO NOT EDIT BY HAND ====
const KEY_LEN: usize = 64;

// --- COVER KEY ---
const OBF_COVER_SEED: [u8; 16] = [
    0x21, 0xb9, 0x7f, 0x43, 0xad, 0x4f, 0xb3, 0x2e, 0x85, 0xbb, 0x76, 0xc7,
    0x39, 0x23, 0x23, 0x76,
];

const OBF_COVER_KEY: [u8; 64] = [
    0x15, 0x51, 0x38, 0xc4, 0x10, 0x57, 0x25, 0xc4, 0x8b, 0xc3, 0x7f, 0xab,
    0x0e, 0x2f, 0xd6, 0x75, 0xf5, 0x20, 0xbe, 0x05, 0xc9, 0x13, 0x1c, 0xf6,
    0x9f, 0x6c, 0x79, 0x8c, 0xe0, 0xd6, 0xd6, 0x65, 0xaf, 0x11, 0xec, 0x4f,
    0xc1, 0xe7, 0x3e, 0x37, 0xd5, 0xdb, 0x7e, 0x52, 0x24, 0x09, 0x06, 0x97,
    0x64, 0x4c, 0x4a, 0x99, 0x7f, 0x4d, 0x87, 0x35, 0x56, 0x8b, 0x24, 0xd4,
    0x0a, 0x4d, 0x77, 0x1b,
];

const COVER_KEY_CHECKSUM: [u8; 8] = [
    0x85, 0x4e, 0x6a, 0x40, 0x40, 0xa3, 0xf0, 0xdf,
];

// --- API KEY ---
const OBF_API_SEED: [u8; 16] = [
    0x55, 0xc3, 0x5c, 0xaa, 0x3f, 0x3c, 0x32, 0x6d, 0xaa, 0x63, 0x0f, 0x90,
    0x39, 0x5d, 0x66, 0x36,
];

const OBF_API_KEY: [u8; 64] = [
    0x24, 0x99, 0x56, 0x2b, 0x80, 0x20, 0xc1, 0xb7, 0xf6, 0x7d, 0x74, 0x91,
    0xe4, 0xc3, 0x7f, 0x67, 0x1a, 0x0e, 0x8a, 0xf3, 0x7f, 0x50, 0xaf, 0x2e,
    0x05, 0xd5, 0xa7, 0xb0, 0xbe, 0x6e, 0x31, 0x11, 0x40, 0xf3, 0x42, 0xad,
    0x31, 0xf6, 0xcb, 0xea, 0xb5, 0xba, 0xdd, 0xd0, 0x8e, 0x56, 0x55, 0x8c,
    0xb4, 0xe5, 0x1d, 0x82, 0x69, 0x0c, 0x3f, 0xb2, 0x30, 0x82, 0xa7, 0xf4,
    0x9b, 0xba, 0x9b, 0x70,
];

const API_KEY_CHECKSUM: [u8; 8] = [
    0xe2, 0x09, 0x02, 0x55, 0x83, 0xee, 0xf0, 0x07,
];

// --- MONITOR KEY ---
const OBF_MONITOR_SEED: [u8; 16] = [
    0x24, 0xde, 0x93, 0x91, 0xa4, 0xb0, 0xa0, 0xd2, 0x0c, 0x10, 0xc8, 0xf5,
    0xf7, 0x74, 0x2d, 0xd2,
];

const OBF_MONITOR_KEY: [u8; 64] = [
    0x38, 0x37, 0xff, 0xc7, 0x78, 0x91, 0x2a, 0x40, 0x64, 0x78, 0x6f, 0xbd,
    0x70, 0x66, 0x4a, 0x4f, 0x54, 0xa5, 0x39, 0x3b, 0xea, 0xfa, 0xc5, 0x9d,
    0xd0, 0xd9, 0xf9, 0x38, 0xe6, 0x84, 0xee, 0x1b, 0x1a, 0xd3, 0x2c, 0xaf,
    0x9f, 0x7b, 0x8b, 0xee, 0x34, 0xcd, 0x05, 0x8e, 0x86, 0x8d, 0xa4, 0x2f,
    0xd5, 0xbe, 0xc1, 0x14, 0x04, 0x2b, 0x61, 0xa5, 0xf1, 0x94, 0x27, 0x48,
    0x2a, 0x9b, 0x55, 0x6c,
];

const MONITOR_KEY_CHECKSUM: [u8; 8] = [
    0x9e, 0x59, 0x6d, 0xb4, 0x3e, 0xcb, 0xc3, 0xbb,
];
// ==== END generated ====

/// Derive keystream: `SHA256(seed || [i])` blocks concatenated.
fn keystream(seed: &[u8], length: usize) -> Zeroizing<Vec<u8>> {
    let mut out = Zeroizing::new(Vec::with_capacity(length + 32));
    let mut i: u8 = 0;
    while out.len() < length {
        let mut hasher = Sha256::new();
        hasher.update(seed);
        hasher.update([i]);
        out.extend_from_slice(&hasher.finalize());
        i = i.wrapping_add(1);
    }
    out.truncate(length);
    out
}

fn deobfuscate_key(seed: &[u8], obf_key: &[u8], checksum: &[u8; 8]) -> Zeroizing<Vec<u8>> {
    let ks = keystream(seed, KEY_LEN);
    let mut key = Zeroizing::new(vec![0u8; KEY_LEN]);
    for idx in 0..KEY_LEN {
        key[idx] = obf_key[idx] ^ ks[idx];
    }

    let digest = Sha256::digest(&key[..]);
    assert_eq!(
        &digest[..8],
        checksum,
        "signing key reconstruction failed — checksum mismatch",
    );
    key
}

/// Reconstruct cover signing key.
pub fn deobfuscate_cover_key() -> Zeroizing<Vec<u8>> {
    deobfuscate_key(&OBF_COVER_SEED, &OBF_COVER_KEY, &COVER_KEY_CHECKSUM)
}

/// Reconstruct API request signing key.
pub fn deobfuscate_api_key() -> Zeroizing<Vec<u8>> {
    deobfuscate_key(&OBF_API_SEED, &OBF_API_KEY, &API_KEY_CHECKSUM)
}

/// Reconstruct Monitor telemetry signing key.
pub fn deobfuscate_monitor_key() -> Zeroizing<Vec<u8>> {
    deobfuscate_key(&OBF_MONITOR_SEED, &OBF_MONITOR_KEY, &MONITOR_KEY_CHECKSUM)
}

/// Compute HMAC-SHA256 for Cover URL tokens.
pub fn sign_cover_base64url(payload: &[u8]) -> Result<String, String> {
    let key = deobfuscate_cover_key();
    let mut mac = <HmacSha256 as Mac>::new_from_slice(&key)
        .map_err(|_| "invalid cover signing key".to_string())?;
    mac.update(payload);
    let signature = mac.finalize().into_bytes();
    Ok(URL_SAFE_NO_PAD.encode(signature))
}

/// Compute HMAC-SHA256 for API Requests.
pub fn sign_api_base64url(payload: &[u8]) -> Result<String, String> {
    let key = deobfuscate_api_key();
    let mut mac = <HmacSha256 as Mac>::new_from_slice(&key)
        .map_err(|_| "invalid api signing key".to_string())?;
    mac.update(payload);
    let signature = mac.finalize().into_bytes();
    Ok(URL_SAFE_NO_PAD.encode(signature))
}

/// Compute HMAC-SHA256 for Monitor Telemetry Requests.
pub fn sign_monitor_base64url(payload: &[u8]) -> Result<String, String> {
    let key = deobfuscate_monitor_key();
    let mut mac = <HmacSha256 as Mac>::new_from_slice(&key)
        .map_err(|_| "invalid monitor signing key".to_string())?;
    mac.update(payload);
    let signature = mac.finalize().into_bytes();
    Ok(URL_SAFE_NO_PAD.encode(signature))
}

/// Legacy alias for API request signing.
pub fn sign_base64url(payload: &[u8]) -> Result<String, String> {
    sign_api_base64url(payload)
}

/// Compute SHA-256 hex string of a byte slice.
pub fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}
